version: '3.8'

services:
  filecat:
    build: .
    container_name: filecat_app
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./auth:/var/www/html/auth
      - ./messages:/var/www/html/messages
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: unless-stopped
